export default [
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 1,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 2,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 3,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    }, 
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 4,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 5,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 6,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 7,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    }, 
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 8,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 9,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 10,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 11,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },  
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 12,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 13,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 14,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 15,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 16,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 17,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 18,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 19,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 20,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 21,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 22,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 23,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 24,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 25,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 26,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 27,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 28,
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 29,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "cloudy",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 30,
        isApplied: 1, 
        created_at_month: 6,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 1,
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 2,
        isApplied: 1, 
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "cloudy",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 3,
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 4,
        isApplied: 1, 
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "cloudy",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 5,
        isApplied: 1, 
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 6,
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 7,
        isApplied: 1, 
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "few clouds",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 8,
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "clear sky",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 9,
        isApplied: 1, 
        created_at_month: 7,
        created_at_year: 2024
    },
    {
        description: "cloudy",
        temperature: 22.1,
        UVI: 4.1,
        country: "CA",
        city: "Vancouver",
        created_at_day: 10,
        isApplied: 1, 
        created_at_month: 7,
        created_at_year: 2024
    },
]